### ISSUE TITLE
# 关于语言模型的调用

### ISSUE THREAD

**Issue by KissMyLady** [LC1332/Chat-Haruhi-Suzumiya#12]
## 调用第三方语言模型可实现角色问答

![2023-08-09_092844](https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/45792040/da2a0c49-c7bd-4ca6-9e93-d4893c86204e)

因为没有openAI的账号, 所以换了一个JinaAI的token, 发现也是可以的. 

**我想请问下大佬, 能否将这个数据格式自己写一遍, 使用开源的语言模型进行推理?**

**或者实现对messages内容的解析, 这样可以吗?**

```python
messages = [
    SystemMessage(content=self.system_prompt),
    HumanMessage(content=story)
]
```

chat使用JinaChat
```python
from langchain.chat_models import JinaChat


messages = self.organize_message_langchain(story, history_chat, history_response, new_query)

jinChat_key = "token"
if not "OPENAI_API_KEY" in os.environ.keys():
    # chat = ChatOpenAI(temperature=0, openai_api_key=self.api_key, model_kwargs={"stop": ["\n", "」"]})
    chat = JinaChat(temperature=0, jinachat_api_key=self.api_key, model_kwargs={"stop": ["\n", "」"]})
else:
    # chat = ChatOpenAI(temperature=0, model_kwargs={"stop": ["\n", "」"]})
    chat = JinaChat(temperature=0, model_kwargs={"stop": ["\n", "」"]})

return_msg = chat(messages)
response = return_msg.content + "」"
```

## messages 的数据格式

![2023-08-08_135519](https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/45792040/6cc0aea1-ce5f-4cf0-93af-6bf544ba2bf2)

**Comment by LC1332** [comment]
我觉得你的尝试非常不错，实际上我在考虑重构我的项目，通过委托的方式可以切换不同的LLM放进去。你知乎找一下我主页 https://www.zhihu.com/people/cheng-li-47 发一下我微信号哈哈哈
