### ISSUE TITLE
大模型创业项目

### ISSUE THREAD

**Issue by Ligoml** [LC1332/Chat-Haruhi-Suzumiya#2]
hi 同学你好，我们目前在筹备大模型创业项目相关的活动，在github上偶然看到你的项目，对你们的项目很感兴趣，我们可以提供技术&资金支持，不知道是否有兴趣详细沟通呢～如果您有意向的话，可以添加我的微信：xxf15564776686～

**Comment by LC1332** [comment]
你们是Robin老师搞的10亿文心基金吗哈哈哈哈

**Comment by LC1332** [comment]
我中午一点加你 早上先干点活儿。。

**Comment by LC1332** [comment]
已经联系上 建立微信群 Let me close the issue
