### ISSUE TITLE
论文有部分地方不理解，求解释

### ISSUE THREAD

**Issue by stevezxzhou** [LC1332/Chat-Haruhi-Suzumiya#21]
在生成对话的章节中，您提到

对于每一个对话 $d$ ，我们都找到角色 $R$ 说话的第一句话。并且在这句对话开始前，将 $d$ 切割为 $d^L$ 和 $d^R$ 左右两段对话。并且我们在 $d^L$ 的两端插入 User Message 的special token，在 $d^R$ 的两端插入 AI Message 的 special token。对所有的 $M$ 个 story我们都进行这样的操作，这样我们希望语言模型会在这 $M$ 个例子的基础上， 在我们给定 $q_1$ 的基础上，去模拟生成对应的对话 $d'$ 。生成后的 $d'$ 会成为语言模型的微调数据。即

$d'(q_1) = LLM( s_R, (d^1_M, 1^R_M),  ..., (d^L_M, d^R_M), q_1 )$

请问能对这里做更多解释吗？将d分成left和right的分割标准是什么？为什么left对应的是user而right对应的是ai？另外，是生成每个$d'$的时候都会将$D$中的每个故事$d$（一个$M$个）分割后得到left-right pair放到prompt里面吗？

感激~

**Comment by LC1332** [comment]
这部分对应 https://github.com/LC1332/Chat-Haruhi-Suzumiya/blob/main/kyon_generator/chat2dialogue.py 的代码

所以你可以在数据集中发现我们大约有超过1/5的概率，一句对话可以让chatbot一次性生成多次连续的对话。左侧在实际使用的时候更接近用户的问话。 我记得这个在文档里面有个配图来解释。

**Comment by LC1332** [comment]
let me closed the issue
