### ISSUE TITLE
微调模型和代码发布 chatglm2-lora model released

### ISSUE THREAD

**Issue by rayvzn119** [LC1332/Chat-Haruhi-Suzumiya#22]

**Comment by LC1332** [comment]
we actually released our chatglm2 lora model on https://huggingface.co/silk-road/Chat-Haruhi-Fusion_B

the simple version of inference code is in cleaning, but any developer tried glm lora before should be able to run it easily.

**Comment by LC1332** [comment]
其实论文报告里说的挺清楚的-o- 要不再努力看一下

**Comment by LC1332** [comment]
Let me closed the issue
