### ISSUE TITLE
chat凉宫春日的CoT

### ISSUE THREAD

**Issue by stevezxzhou** [LC1332/Chat-Haruhi-Suzumiya#24]
您在赞助的页面提到：

“因为Chat凉宫春日采用了类似CoT的策略，相比于通常聊天，要贵上10-20倍，目前API token都采用社区捐赠的费用来支持。”。

但我阅读了您的论文和代码（https://github.com/LC1332/Chat-Haruhi-Suzumiya/blob/main/kyon_generator/ChatGPT_for_generation.py ）
的时候，没找到CoT相关的论述和代码，请问CoT相应的文档及其相应的代码是哪些文件？

谢谢~

**Comment by Hezhexi2002** [comment]
> 您在赞助的页面提到：
> 
> “因为Chat凉宫春日采用了类似CoT的策略，相比于通常聊天，要贵上10-20倍，目前API token都采用社区捐赠的费用来支持。”。
> 
> 但我阅读了您的论文和代码（https://github.com/LC1332/Chat-Haruhi-Suzumiya/blob/main/kyon_generator/ChatGPT_for_generation.py ） 的时候，没找到CoT相关的论述和代码，请问CoT相应的文档及其相应的代码是哪些文件？
> 
> 谢谢~

在report中的`ChatBot核心的构造`部分有说明CoT的工作原理

**Comment by LC1332** [comment]
这个我回头改一下，原来在初步实验用了严格为CoT的方法，现在的方法严格来说不是CoT。

**Comment by LC1332** [comment]
我在想如果chatbot想要保住一些秘密，可能还是需要去用一些CoT的方法。

**Comment by LC1332** [comment]
不过确实有误导，我把github上这部分删了修改一下吧
