### ISSUE TITLE
关于训练数据使用问题

### ISSUE THREAD

**Issue by lucasjinreal** [LC1332/Chat-Haruhi-Suzumiya#29]
Hi，请问一下，

1. 训练的问题是否要加入角色名字？如果不加入角色名名字，语料里面很多对话是说不通的，例如汤师爷在跟财主和农民对话的时候风格是完全不同的。如果加入，如何加入？用户是否每次对话都要输入角色名字？

**Comment by LC1332** [comment]
https://www.zhihu.com/people/cheng-li-47 你要不去知乎上给我发一下微信。。

训练prompt的组织在https://huggingface.co/datasets/silk-road/Chat-Haruhi-Fusion-A_B

实际调用的比较好的参考是https://github.com/LC1332/Haruhi-2-Dev在这里有个printLLM给了prompt的组织方式

实际对话的时候prompt是比较动态组织的

**Comment by lucasjinreal** [comment]
如果没有理解错的话，输入是带有角色名，输出也是带有角色名。
用户每次输入的时候要自己指定自己的角色名么？

这种操作逻辑似乎跟minimax不太一样啊

**Comment by lucasjinreal** [comment]
![image](https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/21303438/1ed4eb6c-1fcd-4d2b-a9c4-6086da8cf6e2)

另外我kan数据第一条就不太对，阿紫一开始说 我说皇上真聪明，最后也是  我说皇上真聪明，这咋学？

**Comment by LC1332** [comment]
对的，用户输入需要指定自己的角色名～（当然多啦A梦蜡笔小新这种也都可以） 旁白是一个特殊角色（照理说旁白的话没有引号）

**Comment by lucasjinreal** [comment]
但是更自然的角色对话，应该是让角色自然而然的记住自己的角色和定位，以及思考方式。例如Glow 和 CharacterAI。
这一块楼主有何思考么？ 因为仔细体验过cAI的产品，他解决的需求才是真正的需求，而不是纯粹的去学习剧本。例如在cAI上跟苏格拉底聊天，你会发现作为用户的你只是一个跟他聊天的路人，你说的每一句话他都会给你思辨，反驳，非常符合一个哲学家的特质。

我想表达的是，用户实际上并不是很关心我是以农民或者财主的身份去和汤师爷对话，用户真正的需求应该是非常自然的，相当于是汤师爷跟一个剧外人物对话，如此这般的自然。如果要做到cAI这种水平，感觉多角色的语料不太好学到此类特征，你认为呢

**Comment by lucasjinreal** [comment]
换句话说，为了让模型能更自然的对话，把输入的角色全部删掉，模型是否能学到该角色应有的特质？

**Comment by LC1332** [comment]
我觉得你说的有道理，这样和我们原始工作的出发点就不一样了。比如哈利波特向麻瓜怎么讨论，我感觉就很难定义了。我们设计的原始动机希望去考虑用户在剧中去cosplay一个角色一起玩，而不是让哈利波特向你介绍魔法世界是什么。主要是我后面想继续做story teller的话，希望剧中沉浸感强一点。如果是单chatbot对话确实你说的那些也要考虑到。

**Comment by lucasjinreal** [comment]
@LC1332  确实，仔细思考了一下，感觉的确可以看作是两个不同的任务。我有个角色对话交流群，可否邀请大佬垂加？

也可以宣传、探讨一下story teller的主题，这里面很多在收集角色对话的人。

![116620a2286c731828f0984cc81c4ca](https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/21303438/457831f8-1e0e-44d9-85b3-85f331be0b54)

**Comment by LC1332** [comment]
我一会儿加一下；

**Comment by Lam1360** [comment]
> @LC1332 确实，仔细思考了一下，感觉的确可以看作是两个不同的任务。我有个角色对话交流群，可否邀请大佬垂加？
> 
> 也可以宣传、探讨一下story teller的主题，这里面很多在收集角色对话的人。
> 
> ![116620a2286c731828f0984cc81c4ca](https://user-images.githubusercontent.com/21303438/264245743-457831f8-1e0e-44d9-85b3-85f331be0b54.jpg)

我也对这个感兴趣，可以把我拉进群吗

**Comment by LC1332** [comment]
你 @lucasjinreal 让他重新发个二维码哈哈哈

**Comment by Lam1360** [comment]
@lucasjinreal 二维码可以重新发一下吗，我也对这个很感兴趣

**Comment by Vincentyua** [comment]
@lucasjinreal 同想加入群，求拉

**Comment by melody-rain** [comment]
> 但是更自然的角色对话，应该是让角色自然而然的记住自己的角色和定位，以及思考方式。例如Glow 和 CharacterAI。 这一块楼主有何思考么？ 仔细体验过cAI的产品，他解决的需求才是真正的需求，用户可以以一个剧外人的身份自然而然的和角色对话，而不是纯粹的去学习剧本。例如在cAI上跟苏格拉底聊天，你会发现作为用户的你只是一个跟他聊天的路人，你说的每一句话他都会给你思辨，反驳，非常符合一个哲学家的特质。
> 
> 我想表达的是，用户实际上并不是很关心我是以农民或者财主的身份去和汤师爷对话，用户真正的需求应该是非常自然的，相当于是汤师爷跟一个剧外人物对话，如此这般的自然。如果要做到cAI这种水平，感觉多角色的语料不太好学到此类特征，你认为呢

@lucasjinreal @LC1332  感觉CharacterAI是用一个模型支持，通过system prompt + in context learning + 知识库支持定制不同的角色的吧？不然每个角色都弄一个模型不太现实吧。如果是一个模型的话，意味着这个模型的世界知识要足够的多？或者ICL的能力非常强？

所以到底是该努力做个够强的foundation model还是怎么着...

**Comment by melody-rain** [comment]
再就是，从 @LC1332 报告里看，用chatGPT/chatGLM2未经模型训练，也可以进行角色扮演，所以可能用这俩模型，用户自己的role叫什么名字就无所谓了吧？
只是自己训练的模型，由于世界知识不够强，所以希望用户自己命名的role能和目标角色有强关联？

**Comment by coranholmes** [comment]
@lucasjinreal 我也求拉一下群，谢谢~
