### ISSUE TITLE
很有趣的应用

### ISSUE THREAD

**Issue by zhongtao93** [LC1332/Chat-Haruhi-Suzumiya#4]
想问一下，现在 https://huggingface.co/spaces/silk-road/ChatHaruhi 上的效果，是直接用chatgpt的端口的结果吗，还是chatglm2呢，或者微调后的chatglm2. 另外可以有readme介绍一下notebook的功能么，有点看不懂:(
<img width="1551" alt="image" src="https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/15263824/bf3e45dc-582b-4f7b-985b-2d7895fa4414">

**Comment by LC1332** [comment]
这个现在应该是gradio server上的效果～ 而不是glm2 我们正在把这两个整合

**Comment by lucasjinreal** [comment]
<img width="824" alt="image" src="https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/21303438/916fd48a-e825-4c6c-8ced-3b78908b8db6">

**Comment by LC1332** [comment]
那个token挂掉了，等周一arxiv一起我们重新更新一下demo；
