### ISSUE TITLE
如何添加openai的代理网址呢?

### ISSUE THREAD

**Issue by E-sion** [LC1332/Chat-Haruhi-Suzumiya#43]
目前使用的是其他网页代理的chatgpt的api,不知道应该如何修改 openai.api_key_path的值为代理网址

**Comment by LC1332** [comment]
你能够给网页代理那个项目的链接发一下吗 我回头做个分支。

**Comment by E-sion** [comment]
https://github.com/E-sion/NEEDY-SLACK-Haruhi2/blob/main/ChatHaruhi/LangChainGPT.py
第49行和第50行简单实现了这个功能，不过需要读取env文件里设定的值。

**Comment by LC1332** [comment]
其实现在有一些能从网页里面去读网页那个token的临时代理，那些也可以集成一下 那些不消耗api费用

**Comment by E-sion** [comment]
哦哦，大致理解了，是不是类似free gpt4的方式来使用openai API的服务。
https://github.com/xtekky/gpt4free
