### ISSUE TITLE
关于story的一些疑问

### ISSUE THREAD

**Issue by Louis-y-nlp** [LC1332/Chat-Haruhi-Suzumiya#44]
https://github.com/LC1332/Chat-Haruhi-Suzumiya/blob/main/ChatHaruhi2.0/ChatHaruhi/ChatHaruhi.py#L216

为什么这里story会作为user message，而不是system message的一部分呢？

**Comment by LC1332** [comment]
其实在chatgpt3.5的时候 user message和system message使用影响是不大的，如果这里改成system message应该影响不大。两者的使用区别在gpt4中才有一定比较大的影响。

**Comment by Louis-y-nlp** [comment]
感谢回复，如果是在gpt4中，是不是story作为system message更符合直觉一点

**Comment by LC1332** [comment]
system message更像一种系统的whisper， story应该是用户提供的context。 我感觉作为user message更合适。 具体还是可以试一下 但是为了chatbot用gpt4有点贵

**Comment by Louis-y-nlp** [comment]
了解了，感谢
