### ISSUE TITLE
百川HF Demo

### ISSUE THREAD

**Issue by sduGuyu** [LC1332/Chat-Haruhi-Suzumiya#48]
好像没实现好，只有百川LLM API的感觉，没角色语料
![image](https://github.com/LC1332/Chat-Haruhi-Suzumiya/assets/83394431/0d96aeb6-8261-4ebe-9f3d-0df67827cd94)

**Comment by LC1332** [comment]
我让 @hhhwmws0117 看一下～百川那个是他接入的 。或者我有空时间看一下。各家的api能力不一样，所以有的api story的reference数量会减少（有可能会减少到3）

**Comment by hhhwmws0117** [comment]
感谢您的反馈，我们部署时注意到这个问题，百川API在角色扮演上的能力不是很强，我会继续调整下语料的组织，后续会放出（可能）性能更好的版本

**Comment by hhhwmws0117** [comment]
已经修改，地址仍是在原地址

**Comment by LC1332** [comment]
对的，百川连续给进两个user message的时候会忽略后面一个。
