### ISSUE TITLE
我们在多轮对话的实践中发生了人格崩坏，希望得到回复

### ISSUE THREAD

**Issue by Kirovsiki** [LC1332/Chat-Haruhi-Suzumiya#59]
在实际的对话中，我们发现用一些特定的对话会让模型直接承认自己是GPT，是否需要使用某种限制强行规避呢？例如请给我十个例子或者是请给我多段范例一类的。

**Comment by LC1332** [comment]
你要不知乎上https://www.zhihu.com/people/cheng-li-47 私信一下我联系方式  然后看一看例子？ 目前history限制了1000个token左右 如果对话轮数特别多 有可能会有崩坏，可能要在后面再补一句加强续写的prompt

**Comment by Kirovsiki** [comment]
非常感谢，我马上就去看

**Comment by Kirovsiki** [comment]
感谢，我们成功解决了问题
