### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by LazyGH** [LC1332/Chat-Haruhi-Suzumiya#61]
https://github.com/LC1332/Chat-Haruhi-Suzumiya?tab=readme-ov-file#%E5%9F%BA%E6%9C%AC%E7%9A%84%E5%AE%89%E8%A3%85%E5%92%8C%E4%BD%BF%E7%94%A8

出现了多处 charharuhi，应为 chatharuhi，包括pip install命令中

**Comment by LC1332** [comment]
ok我改一下谢谢！

**Comment by LC1332** [comment]
fixed，谢谢！
