### ISSUE TITLE
关于Haruhi-Zero里角色的jsonl文件

### ISSUE THREAD

**Issue by ShowSwichChen** [LC1332/Chat-Haruhi-Suzumiya#70]
我注意到Haruhi-Zero里导入的角色jsonl文件和ChatHaruhi2.0里的角色jsonl不一样，ChatHaruhi3.0不能使用ChatHaruhi2.0的角色jsonl文件。请问怎么像制作ChatHaruhi2.0的角色jsonl一样制作ChatHaruhi3.0的jsonl文件。

**Comment by LC1332** [comment]
哎呀不好意思。我charharuhi3.0的load_from_jsonl 还没有经过详细的测试，照理说应该是能够同样载入的。 我之后有时间调试一下。 其实就是复用load_from_hf的代码就行。 我回头有空的时候测一下，这两天写别的代码耽搁了。

**Comment by ShowSwichChen** [comment]
我发现我之前制做jsonl文件里缺少bge_zh_s15，现在我重写了package_role函数后的jsonl文件现在在ChatHaruhi3.0也可以使用了。

**Comment by LC1332** [comment]
太好了。
